// Base loader template for Squadron WASM workers in Chrome Extension Manifest V3
// The dart2wasm runtime will be inlined here by the patch script

self.dart2wasm_runtime = {};
// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
self.dart2wasm_runtime.compileStreaming = async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
self.dart2wasm_runtime.compile = async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
self.dart2wasm_runtime.instantiate = async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
self.dart2wasm_runtime.invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: Date.now,
      _7: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _8: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _9: () => new Error().stack,
      _18: (exn) => exn.toString(),
      _19: (exn) => exn.stack,
      _20: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _33: s => JSON.stringify(s),
      _34: s => printToConsole(s),
      _35: (o, p, r) => o.replaceAll(p, () => r),
      _37: Function.prototype.call.bind(String.prototype.toLowerCase),
      _38: s => s.toUpperCase(),
      _39: s => s.trim(),
      _42: (string, times) => string.repeat(times),
      _43: Function.prototype.call.bind(String.prototype.indexOf),
      _44: (s, p, i) => s.lastIndexOf(p, i),
      _45: (string, token) => string.split(token),
      _46: Object.is,
      _49: (o, t) => typeof o === t,
      _50: (o, c) => o instanceof c,
      _51: o => Object.keys(o),
      _72: (o) => !!o,
      _81: () => new Array(),
      _82: x0 => new Array(x0),
      _84: x0 => x0.length,
      _86: (x0,x1) => x0[x1],
      _87: (x0,x1,x2) => { x0[x1] = x2 },
      _91: (x0,x1,x2) => new DataView(x0,x1,x2),
      _93: x0 => new Int8Array(x0),
      _94: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _95: x0 => new Uint8Array(x0),
      _97: x0 => new Uint8ClampedArray(x0),
      _99: x0 => new Int16Array(x0),
      _101: x0 => new Uint16Array(x0),
      _103: x0 => new Int32Array(x0),
      _105: x0 => new Uint32Array(x0),
      _107: x0 => new Float32Array(x0),
      _109: x0 => new Float64Array(x0),
      _134: x0 => x0.random(),
      _137: () => globalThis.Math,
      _150: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _154: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _156: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _157: (x0,x1) => x0.exec(x1),
      _158: (x0,x1) => x0.test(x1),
      _159: x0 => x0.pop(),
      _161: o => o === undefined,
      _163: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _165: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _166: o => o instanceof RegExp,
      _167: (l, r) => l === r,
      _168: o => o,
      _169: o => o,
      _170: o => o,
      _171: b => !!b,
      _172: o => o.length,
      _174: (o, i) => o[i],
      _175: f => f.dartFunction,
      _176: () => ({}),
      _177: () => [],
      _179: () => globalThis,
      _180: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _182: (o, p) => o[p],
      _183: (o, p, v) => o[p] = v,
      _184: (o, m, a) => o[m].apply(o, a),
      _186: o => String(o),
      _187: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _188: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._188(f,arguments.length,x0) }),
      _189: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._189(f,arguments.length,x0,x1) }),
      _190: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _191: o => [o],
      _192: (o0, o1) => [o0, o1],
      _193: (o0, o1, o2) => [o0, o1, o2],
      _194: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _195: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _196: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _199: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _205: x0 => new ArrayBuffer(x0),
      _208: x0 => x0.index,
      _210: x0 => x0.flags,
      _211: x0 => x0.multiline,
      _212: x0 => x0.ignoreCase,
      _213: x0 => x0.unicode,
      _214: x0 => x0.dotAll,
      _215: (x0,x1) => { x0.lastIndex = x1 },
      _217: (o, p) => o[p],
      _238: (x0,x1) => globalThis.fetch(x0,x1),
      _240: (x0,x1,x2) => x0.postMessage(x1,x2),
      _241: x0 => x0.close(),
      _242: () => new MessageChannel(),
      _243: (x0,x1) => x0.push(x1),
      _244: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._244(f,arguments.length,x0) }),
      _245: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._245(f,arguments.length,x0) }),
      _246: x0 => new Worker(x0),
      _247: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._247(f,arguments.length,x0) }),
      _248: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._248(f,arguments.length,x0) }),
      _249: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._249(f,arguments.length,x0) }),
      _250: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._250(f,arguments.length,x0) }),
      _251: (x0,x1,x2) => x0.postMessage(x1,x2),
      _252: x0 => x0.terminate(),
      _254: () => globalThis.self,
      _255: x0 => x0.close(),
      _256: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._256(f,arguments.length,x0) }),
      _257: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._257(f,arguments.length,x0) }),
      _258: (x0,x1,x2) => x0.postMessage(x1,x2),
      _259: (x0,x1) => x0.postMessage(x1),
      _260: x0 => globalThis.URL.revokeObjectURL(x0),
      _261: x0 => ({type: x0}),
      _262: (x0,x1) => new Blob(x0,x1),
      _263: x0 => globalThis.URL.createObjectURL(x0),
      _264: (x0,x1) => globalThis.Object.is(x0,x1),
      _265: (x0,x1) => x0.at(x1),
      _266: x0 => x0.entries(),
      _267: x0 => x0.values(),
      _268: x0 => globalThis.BigInt(x0),
      _269: () => new Map(),
      _270: (x0,x1,x2) => x0.set(x1,x2),
      _271: () => new Set(),
      _272: (x0,x1) => x0.add(x1),
      _273: x0 => x0.toString(),
      _274: x0 => x0.getTime(),
      _275: x0 => x0.length,
      _277: x0 => x0.buffer,
      _278: o => o instanceof Array,
      _285: (a, s) => a.join(s),
      _289: a => a.length,
      _291: (a, i) => a[i],
      _292: (a, i, v) => a[i] = v,
      _297: o => o instanceof Uint8Array,
      _298: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _299: o => o instanceof Int8Array,
      _300: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _301: o => o instanceof Uint8ClampedArray,
      _302: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _303: o => o instanceof Uint16Array,
      _304: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _305: o => o instanceof Int16Array,
      _306: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _307: o => o instanceof Uint32Array,
      _308: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _309: o => o instanceof Int32Array,
      _310: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _313: o => o instanceof Float32Array,
      _314: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _315: o => o instanceof Float64Array,
      _316: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _317: (t, s) => t.set(s),
      _319: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _321: o => o.buffer,
      _322: o => o.byteOffset,
      _323: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _324: (b, o) => new DataView(b, o),
      _325: (b, o, l) => new DataView(b, o, l),
      _326: Function.prototype.call.bind(DataView.prototype.getUint8),
      _327: Function.prototype.call.bind(DataView.prototype.setUint8),
      _328: Function.prototype.call.bind(DataView.prototype.getInt8),
      _329: Function.prototype.call.bind(DataView.prototype.setInt8),
      _330: Function.prototype.call.bind(DataView.prototype.getUint16),
      _331: Function.prototype.call.bind(DataView.prototype.setUint16),
      _332: Function.prototype.call.bind(DataView.prototype.getInt16),
      _333: Function.prototype.call.bind(DataView.prototype.setInt16),
      _334: Function.prototype.call.bind(DataView.prototype.getUint32),
      _335: Function.prototype.call.bind(DataView.prototype.setUint32),
      _336: Function.prototype.call.bind(DataView.prototype.getInt32),
      _337: Function.prototype.call.bind(DataView.prototype.setInt32),
      _342: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _343: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _344: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _345: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _346: Function.prototype.call.bind(Number.prototype.toString),
      _347: Function.prototype.call.bind(BigInt.prototype.toString),
      _348: Function.prototype.call.bind(Number.prototype.toString),
      _2197: () => globalThis.window,
      _2241: x0 => x0.location,
      _2543: x0 => x0.pathname,
      _2584: x0 => x0.filename,
      _2585: x0 => x0.lineno,
      _2730: x0 => x0.port1,
      _2731: x0 => x0.port2,
      _2734: (x0,x1) => { x0.onmessage = x1 },
      _2736: (x0,x1) => { x0.onmessageerror = x1 },
      _2791: (x0,x1) => { x0.onmessage = x1 },
      _2802: (x0,x1) => { x0.onmessage = x1 },
      _2804: (x0,x1) => { x0.onmessageerror = x1 },
      _2806: (x0,x1) => { x0.onerror = x1 },
      _7345: x0 => x0.status,
      _7346: x0 => x0.ok,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}

// No-op logger by default to prevent sensitive data leakage
// Set to console to enable logging for debugging
//
// const logger = console;
const logger = { 
  log: () => {},
  error: () => {}
};

// Global error handlers for the worker
self.addEventListener('error', (event) => {
  logger.error('[WASM Loader] Uncaught error in worker:', event.error, event);
  const ts = (Date.now() - Date.UTC(2020, 1, 2)) * 1000;
  postMessage([
    ts,
    null,
    [
      "$!",
      `Uncaught error in worker: ${event.error?.message || event.message}`,
      event.error?.stack || null,
      null,
    ],
    null,
    null,
  ]);
});

self.addEventListener('unhandledrejection', (event) => {
  logger.error('[WASM Loader] Unhandled promise rejection in worker:', event.reason);
  const ts = (Date.now() - Date.UTC(2020, 1, 2)) * 1000;
  postMessage([
    ts,
    null,
    [
      "$!",
      `Unhandled rejection: ${event.reason?.message || event.reason}`,
      event.reason?.stack || null,
      null,
    ],
    null,
    null,
  ]);
});

(async function () {
    const url = "/assets/packages/cardano_flutter_sdk/workers/wallet_tasks.web.g.dart.wasm";
    logger.log('[WASM Loader] Loading WASM from:', url);

    const workerUri = new URL(url.replaceAll('"', '\\"'), self.location.origin).href;
    logger.log('[WASM Loader] Resolved worker URI:', workerUri);

    try {
      let instantiatedApp;
      try {
        logger.log('[WASM Loader] Fetching WASM module...');
        const response = await fetch(workerUri);
        logger.log('[WASM Loader] Fetch response status:', response.status, response.statusText);

        if (!response.ok) {
          throw new Error(`Failed to fetch WASM: ${response.status} ${response.statusText}`);
        }

        logger.log('[WASM Loader] Compiling and instantiating WASM module...');
        // Use compileStreaming (not raw WebAssembly.compileStreaming) so the
        // dart2wasm runtime includes the required {builtins: ['js-string']} option.
        const compiledApp = await self.dart2wasm_runtime.compileStreaming(response);
        // instantiate() also calls $setThisModule — required since dart2wasm 3.11.
        instantiatedApp = await compiledApp.instantiate({});
        logger.log('[WASM Loader] WASM module instantiated successfully');
      } catch (exception) {
        logger.error(
          `[WASM Loader] Failed to fetch and instantiate wasm module ${workerUri}:`,
          exception
        );
        logger.error('[WASM Loader] Exception stack:', exception.stack);
        logger.error('[WASM Loader] See https://dart.dev/web/wasm for more information.');
        throw new Error(
          exception.message ?? "Unknown error when instantiating worker module",
        );
      }
      try {
        logger.log('[WASM Loader] Invoking WASM module main...');
        instantiatedApp.invokeMain();
        logger.log('[WASM Loader] Successfully loaded and invoked', workerUri);
      } catch (exception) {
        logger.error(
          `[WASM Loader] Exception while invoking wasm module ${workerUri}:`,
          exception
        );
        logger.error('[WASM Loader] Exception stack:', exception.stack);
        throw new Error(
          exception.message ?? "Unknown error when invoking worker module",
        );
      }
    } catch (ex) {
      logger.error('[WASM Loader] Fatal error in loader:', ex);
      logger.error('[WASM Loader] Error stack:', ex.stack);
      const ts = (Date.now() - Date.UTC(2020, 1, 2)) * 1000;
      postMessage([
        ts,
        null,
        [
          "$!",
          `Failed to load Web Worker from ${workerUri}: ${ex.message || ex}`,
          ex.stack || null,
          null,
        ],
        null,
        null,
      ]);
    }
  })();
  
